// <auto-generated />
using System;
using API.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(NVcontext))]
    partial class NVcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.EF.Nhanvien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diachi")
                        .HasColumnType("char(30)");

                    b.Property<string>("Gioitinh")
                        .HasColumnType("char(4)");

                    b.Property<string>("Manv")
                        .HasColumnType("char(10)");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("Date");

                    b.Property<string>("Phong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("char(20)");

                    b.HasKey("ID");

                    b.ToTable("Nhanvien");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Diachi = "Bac Ninh",
                            Gioitinh = "Nam",
                            Manv = "CT010304",
                            Ngaysinh = new DateTime(1998, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phong = "PM",
                            Ten = "Hoang Tien Binh"
                        },
                        new
                        {
                            ID = 2,
                            Diachi = "Thai Binh",
                            Gioitinh = "Nam",
                            Manv = "CT010305",
                            Ngaysinh = new DateTime(1998, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phong = "PM",
                            Ten = "Hoang Thanh Binh"
                        },
                        new
                        {
                            ID = 3,
                            Diachi = "Bac Ninh",
                            Gioitinh = "Nu",
                            Manv = "CT010306",
                            Ngaysinh = new DateTime(1998, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phong = "App",
                            Ten = "Hoang Thi Binh"
                        },
                        new
                        {
                            ID = 4,
                            Diachi = "Ha Noi",
                            Gioitinh = "Nu",
                            Manv = "CT010307",
                            Ngaysinh = new DateTime(1998, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phong = "Mobile",
                            Ten = "Nguyen Thi A"
                        });
                });

            modelBuilder.Entity("API.EF.User1", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Manv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Passwords");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Manv = "CT010304",
                            Name = "binhht2",
                            Pass = "1234"
                        },
                        new
                        {
                            ID = 2,
                            Manv = "CT010305",
                            Name = "binhht1",
                            Pass = "1234"
                        },
                        new
                        {
                            ID = 3,
                            Manv = "CT010306",
                            Name = "admin",
                            Pass = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
